"""Initial migration

Revision ID: 22cabe4efb61
Revises: 
Create Date: 2026-01-04 22:46:47.605799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cabe4efb61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dataroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataroom_id'), 'dataroom', ['id'], unique=False)
    op.create_index(op.f('ix_dataroom_name'), 'dataroom', ['name'], unique=False)
    op.create_index(op.f('ix_dataroom_owner_id'), 'dataroom', ['owner_id'], unique=False)
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataroom_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataroom_id'], ['dataroom.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_dataroom_id'), 'folder', ['dataroom_id'], unique=False)
    op.create_index(op.f('ix_folder_id'), 'folder', ['id'], unique=False)
    op.create_index(op.f('ix_folder_name'), 'folder', ['name'], unique=False)
    op.create_index(op.f('ix_folder_parent_id'), 'folder', ['parent_id'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_folder_id'), 'file', ['folder_id'], unique=False)
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=False)
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    op.create_table('file_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_share_file_id'), 'file_share', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_share_id'), 'file_share', ['id'], unique=False)
    op.create_index(op.f('ix_file_share_token'), 'file_share', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_share_token'), table_name='file_share')
    op.drop_index(op.f('ix_file_share_id'), table_name='file_share')
    op.drop_index(op.f('ix_file_share_file_id'), table_name='file_share')
    op.drop_table('file_share')
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_index(op.f('ix_file_folder_id'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_folder_parent_id'), table_name='folder')
    op.drop_index(op.f('ix_folder_name'), table_name='folder')
    op.drop_index(op.f('ix_folder_id'), table_name='folder')
    op.drop_index(op.f('ix_folder_dataroom_id'), table_name='folder')
    op.drop_table('folder')
    op.drop_index(op.f('ix_dataroom_owner_id'), table_name='dataroom')
    op.drop_index(op.f('ix_dataroom_name'), table_name='dataroom')
    op.drop_index(op.f('ix_dataroom_id'), table_name='dataroom')
    op.drop_table('dataroom')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
