"""Updated User mode; added StorageGateway and TelegramGateway models

Revision ID: 6cf6f9c9de59
Revises: 22cabe4efb61
Create Date: 2026-01-07 18:58:02.508757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf6f9c9de59'
down_revision: Union[str, None] = '22cabe4efb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TELEGRAM', name='gateway_type', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'type', name='uq_user_gateway_type')
    )
    op.create_index(op.f('ix_storage_gateway_id'), 'storage_gateway', ['id'], unique=False)
    op.create_index(op.f('ix_storage_gateway_owner_id'), 'storage_gateway', ['owner_id'], unique=False)
    op.create_table('telegram_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('storage_gateway_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storage_gateway_id'], ['storage_gateway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_gateway_id'), 'telegram_gateway', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_gateway_storage_gateway_id'), 'telegram_gateway', ['storage_gateway_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_gateway_storage_gateway_id'), table_name='telegram_gateway')
    op.drop_index(op.f('ix_telegram_gateway_id'), table_name='telegram_gateway')
    op.drop_table('telegram_gateway')
    op.drop_index(op.f('ix_storage_gateway_owner_id'), table_name='storage_gateway')
    op.drop_index(op.f('ix_storage_gateway_id'), table_name='storage_gateway')
    op.drop_table('storage_gateway')
    # ### end Alembic commands ###
