"""Added chat id to telegram gateway

Revision ID: 94fbce5d5a08
Revises: 6cf6f9c9de59
Create Date: 2026-01-12 16:11:12.344479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fbce5d5a08'
down_revision: Union[str, None] = '6cf6f9c9de59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_gateway', sa.Column('chat_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_gateway', 'chat_id')
    # ### end Alembic commands ###
